# Generated by Django 2.0.3 on 2018-04-02 23:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('firstname', models.CharField(max_length=100)),
                ('lastname', models.CharField(max_length=100)),
                ('birtday', models.DateField()),
                ('email', models.CharField(max_length=100, primary_key=True, serialize=False, unique=True)),
                ('number', models.CharField(max_length=16)),
                ('status', models.CharField(max_length=1)),
                ('desc', models.TextField(max_length=150)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
