# Generated by Django 2.0.3 on 2018-04-03 00:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paciente',
            name='status',
            field=models.CharField(choices=[('a', 'Active'), ('d', 'desactive')], max_length=1),
        ),
    ]
