# Generated by Django 2.0.4 on 2018-04-16 00:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paciente',
            name='desc',
        ),
        migrations.AlterField(
            model_name='cirujano',
            name='status',
            field=models.CharField(choices=[('A', 'Activo'), ('I', 'Inactivo')], max_length=1),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='pais',
            field=models.CharField(choices=[('ES', 'ESPAÑA'), ('RO', 'ROMA'), ('USA', 'ESTADOS UNIDOS')], max_length=4),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='status',
            field=models.CharField(choices=[('A', 'Activo'), ('I', 'Inactivo')], max_length=1),
        ),
    ]
