# Generated by Django 2.0.4 on 2018-05-06 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='birthdate',
            field=models.DateField(verbose_name='fecha de naciemiento'),
        ),
    ]
