# Generated by Django 2.0.5 on 2018-05-22 01:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='birthdate',
            field=models.DateField(default=datetime.date.today, verbose_name='cumpleaños'),
        ),
    ]
