# Generated by Django 2.0.3 on 2018-04-14 01:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20180414_0140'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paciente',
            name='pais',
            field=models.CharField(max_length=4),
        ),
    ]
