# Generated by Django 2.0.3 on 2018-04-08 02:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20180403_0039'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cirujano',
            fields=[
                ('firstname', models.CharField(max_length=100)),
                ('lastname', models.CharField(max_length=100)),
                ('birtday', models.DateField()),
                ('email', models.CharField(max_length=100, primary_key=True, serialize=False, unique=True)),
                ('number', models.CharField(max_length=16)),
                ('status', models.CharField(choices=[('a', 'Active'), ('d', 'desactive')], max_length=1)),
                ('especialidad', models.TextField(max_length=100)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
