# Generated by Django 2.0.5 on 2018-05-13 16:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20180509_1417'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(default='pic_folder/None/user.png', upload_to='pic_folder/'),
        ),
        migrations.AlterField(
            model_name='user',
            name='birthdate',
            field=models.DateField(default=datetime.date.today, verbose_name='fecha de nacimiento'),
        ),
    ]
