# Generated by Django 2.0.6 on 2018-06-17 05:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Historia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('peso', models.FloatField()),
                ('grupo_san', models.CharField(choices=[('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('AB+', 'AB+'), ('AB-', 'AB-'), ('O+', 'O+'), ('O-', 'O-')], max_length=4, verbose_name='grupo sanguinio')),
                ('tipo_aler', models.CharField(choices=[('DC', 'Dermatitis de contacto'), ('AA', 'Alergia a los alimentos'), ('AM', 'Alergia a los medicamentos')], max_length=30)),
                ('cirugias_ant', models.TextField(max_length=150)),
                ('patologia', models.CharField(max_length=50)),
                ('observaciones', models.TextField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('codigo_Postal', models.CharField(max_length=16)),
                ('pais', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.Country')),
            ],
            options={
                'abstract': False,
            },
            bases=('users.user',),
        ),
        migrations.AddField(
            model_name='historia',
            name='paciente',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='paciente.Paciente'),
        ),
    ]
