# Generated by Django 2.0.6 on 2018-06-25 17:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('codigo_Postal', models.CharField(max_length=16)),
                ('pais', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.Country')),
            ],
            options={
                'abstract': False,
            },
            bases=('users.user',),
        ),
        migrations.CreateModel(
            name='Paquete',
            fields=[
                ('id', models.CharField(max_length=8, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('precio', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Servicio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=120, verbose_name='Nombre')),
                ('descripcion', models.TextField(max_length=150, verbose_name='Descripción')),
                ('precio', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Solicitud_Paquete',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_solicitada', models.DateTimeField(auto_now=True)),
                ('paciente', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='paciente.Paciente')),
                ('paquete', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='paciente.Paquete')),
            ],
        ),
        migrations.AddField(
            model_name='paquete',
            name='servicios',
            field=models.ManyToManyField(to='paciente.Servicio'),
        ),
    ]
