# Generated by Django 2.0.4 on 2018-05-05 17:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('pais', models.CharField(choices=[('ES', 'Espana'), ('EC', 'Ecuador'), ('USA', 'Estados Unidos')], max_length=30)),
            ],
            options={
                'abstract': False,
            },
            bases=('users.user',),
        ),
    ]
