# Generated by Django 2.0.6 on 2018-06-26 08:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('paciente', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paquete',
            name='paciente',
        ),
    ]
