# Generated by Django 2.0.6 on 2018-06-25 06:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('paciente', '0002_solicitud_paquete'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historia',
            name='paciente',
        ),
        migrations.DeleteModel(
            name='Historia',
        ),
    ]
