# Generated by Django 2.0.6 on 2018-06-17 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paciente', '0002_paquete'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paquete',
            name='precio',
            field=models.IntegerField(),
        ),
    ]
