# Generated by Django 2.0.6 on 2018-06-13 22:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('paciente', '0001_initial'),
        ('clinica', '__first__'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Agenda',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Cirugia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30)),
                ('descripcion', models.TextField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Cirugia_Planificada',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.TextField(max_length=150)),
                ('cirugia', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='cirujano.Cirugia')),
            ],
        ),
        migrations.CreateModel(
            name='Cirujano',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
            bases=('users.user',),
        ),
        migrations.CreateModel(
            name='Especialidad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30)),
                ('descripcion', models.TextField()),
            ],
        ),
        migrations.AddField(
            model_name='cirujano',
            name='especialidad',
            field=models.ManyToManyField(to='cirujano.Especialidad'),
        ),
        migrations.AddField(
            model_name='cirugia_planificada',
            name='cirujano',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cirujano.Cirujano'),
        ),
        migrations.AddField(
            model_name='cirugia_planificada',
            name='paciente',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='paciente.Paciente'),
        ),
        migrations.AddField(
            model_name='cirugia_planificada',
            name='quirofano',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='clinica.Quirofano'),
        ),
    ]
