# Generated by Django 2.0.6 on 2018-06-26 08:55

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('paciente', '0001_initial'),
        ('users', '__first__'),
        ('clinica', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Agenda',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Cirugia',
            fields=[
                ('id', models.CharField(max_length=8, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=30)),
                ('tipo', models.CharField(choices=[('OM', 'Cirugía Oral y Maxilofacial'), ('OO', 'Oftalmología y Oculopatía'), ('OT', 'Otorrinolaringología'), ('T', 'Traumatología'), ('PE', 'Cirugía plastica y estética'), ('U', 'Urología'), ('CG', 'Cirugía General')], max_length=50)),
                ('descripcion', models.TextField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Cirugia_Planificada',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(default=datetime.date.today, unique=True, verbose_name='Fecha para la cirugía')),
                ('descripcion', models.TextField(max_length=150)),
                ('cirugia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cirujano.Cirugia')),
            ],
        ),
        migrations.CreateModel(
            name='Cirujano',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
            bases=('users.user',),
        ),
        migrations.CreateModel(
            name='Cita',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_solicitud', models.DateField(auto_now_add=True)),
                ('confirmada', models.BooleanField(default=False)),
                ('descripcion', models.TextField(max_length=150, verbose_name='Descripción')),
                ('medico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cirujano.Cirujano', verbose_name='Médico cirujano')),
                ('paciente', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='paciente.Paciente')),
            ],
        ),
        migrations.CreateModel(
            name='Especialidad',
            fields=[
                ('id', models.CharField(max_length=8, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=30)),
                ('descripcion', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Historia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('peso', models.FloatField(verbose_name='Peso')),
                ('grupo_san', models.CharField(choices=[('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('AB+', 'AB+'), ('AB-', 'AB-'), ('O+', 'O+'), ('O-', 'O-')], max_length=4, verbose_name='Grupo sanguínio')),
                ('tipo_aler', models.CharField(choices=[('DC', 'Dermatitis de contacto'), ('AA', 'Alergia a los alimentos'), ('AM', 'Alergia a los medicamentos')], max_length=30, verbose_name='Tipo de Alergias')),
                ('cirugias_ant', models.TextField(max_length=150, verbose_name='Cirugias anteriores')),
                ('patologia', models.CharField(max_length=50, verbose_name='Patologia')),
                ('observaciones', models.TextField(max_length=150, verbose_name='Observaciones')),
                ('medico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cirujano.Cirujano')),
                ('paciente', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='cirujano.Cita')),
            ],
        ),
        migrations.AddField(
            model_name='cirujano',
            name='especialidad',
            field=models.ManyToManyField(to='cirujano.Especialidad'),
        ),
        migrations.AddField(
            model_name='cirugia_planificada',
            name='cirujano',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cirujano.Cirujano'),
        ),
        migrations.AddField(
            model_name='cirugia_planificada',
            name='paciente',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='cirujano.Cita'),
        ),
        migrations.AddField(
            model_name='cirugia_planificada',
            name='quirofano',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clinica.Quirofano'),
        ),
    ]
