# Generated by Django 2.0.6 on 2018-06-13 23:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cirujano', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cirugia_planificada',
            name='fecha',
            field=models.DateField(default=datetime.date.today, unique=True),
        ),
    ]
