# Generated by Django 2.0.5 on 2018-06-23 14:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('paciente', '0001_initial'),
        ('cirujano', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cita',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_solicitud', models.DateField(auto_now_add=True)),
                ('descripcion', models.TextField(max_length=150, verbose_name='Descripción')),
                ('medico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cirujano.Cirujano', verbose_name='Médico cirujano')),
                ('paciente', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='paciente.Paciente')),
            ],
        ),
    ]
