# Generated by Django 2.0.5 on 2018-06-24 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cirujano', '0002_cita'),
    ]

    operations = [
        migrations.AddField(
            model_name='cita',
            name='confirmada',
            field=models.BooleanField(default=True),
        ),
    ]
