# Generated by Django 2.0.6 on 2018-06-13 23:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cirujano', '0002_cirugia_planificada_fecha'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cirugia_planificada',
            name='cirugia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cirujano.Cirugia'),
        ),
        migrations.AlterField(
            model_name='cirugia_planificada',
            name='quirofano',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clinica.Quirofano'),
        ),
    ]
