# Generated by Django 2.0.6 on 2018-06-25 06:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cirujano', '0004_auto_20180624_1537'),
    ]

    operations = [
        migrations.CreateModel(
            name='Historia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('peso', models.FloatField()),
                ('grupo_san', models.CharField(choices=[('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('AB+', 'AB+'), ('AB-', 'AB-'), ('O+', 'O+'), ('O-', 'O-')], max_length=4, verbose_name='grupo sanguinio')),
                ('tipo_aler', models.CharField(choices=[('DC', 'Dermatitis de contacto'), ('AA', 'Alergia a los alimentos'), ('AM', 'Alergia a los medicamentos')], max_length=30)),
                ('cirugias_ant', models.TextField(max_length=150)),
                ('patologia', models.CharField(max_length=50)),
                ('observaciones', models.TextField(max_length=150)),
                ('medico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cirujano.Cirujano')),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cirujano.Cita')),
            ],
        ),
    ]
