# Generated by Django 2.0.6 on 2018-06-25 11:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cirujano', '0005_historia'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historia',
            name='paciente',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='cirujano.Cita'),
        ),
    ]
