# Generated by Django 2.0.6 on 2018-06-13 23:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clinica', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='horario_quirofano',
            name='quirofano',
        ),
        migrations.DeleteModel(
            name='Horario_Quirofano',
        ),
    ]
