# Generated by Django 2.0.6 on 2018-06-16 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinica', '0002_auto_20180613_1930'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clinica',
            name='id',
            field=models.CharField(max_length=8, primary_key='True', serialize=False),
        ),
    ]
