# Generated by Django 2.0.6 on 2018-06-16 17:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clinica', '0003_auto_20180616_1352'),
    ]

    operations = [
        migrations.RenameField(
            model_name='clinica',
            old_name='correo',
            new_name='email',
        ),
    ]
